### ISSUE TITLE
Reliability review

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#12]
how do I create the reliability review? As a reminder, in the movie coding, we have a review "back-up" option that we use to create the reliability review off of the primary review. 
![screen shot 2014-04-05 at 6 39 11 am](https://cloud.githubusercontent.com/assets/7119634/2622400/ab372f98-bcae-11e3-9b9b-bcd6b858e971.png)

**Comment by dannyl07** [comment]
We'll create the backup feature along with the analysis review type like in movie review.

**Comment by dannyl07** [comment]
Created this feature.  Go into the review admin page to back-up review.
