### ISSUE TITLE
Need to add exception handling when user imports unsupported image formats

### ISSUE THREAD

**Issue by wliu-levansoft** [wliu-levansoft/media-coding#14]
I was trying to import some .CR2 (raw) files and got the following exception when it tried to create a thumbnail.

![screenshot_040514_103241_am](https://cloud.githubusercontent.com/assets/6913896/2622908/257396fa-bccf-11e3-981a-15c9704dfdb5.jpg)

**Comment by dannyl07** [comment]
Fixed it.
