### ISSUE TITLE
Bulk upload hung at 21%

### ISSUE THREAD

**Issue by wliu-levansoft** [wliu-levansoft/media-coding#15]
Although I can't reproduce it, I just want to take a note in case it happens again.

![screenshot_040514_104429_am](https://cloud.githubusercontent.com/assets/6913896/2622934/cba05a9e-bcd0-11e3-8fcc-5934a9ed405e.jpg)

**Comment by dannyl07** [comment]
I've seen this. But it's the debugger that died. I think that's visual studio. It has hung in me with other debugging sessions as well.

**Comment by dannyl07** [comment]
Closing issue since have not been reported outside of the dev environment.  Will keep an eye on it.
