### ISSUE TITLE
Bulk upload browse has different size limit

### ISSUE THREAD

**Issue by wliu-levansoft** [wliu-levansoft/media-coding#16]
I can only upload 5 images using the Browse button.  6 would give me an error.

![screenshot_040514_105502_am](https://cloud.githubusercontent.com/assets/6913896/2622957/447a52fc-bcd2-11e3-87ef-3f055f82433c.jpg)

![screenshot_040514_105304_am](https://cloud.githubusercontent.com/assets/6913896/2622952/fe1c3b7c-bcd1-11e3-95f3-dd271749cb1d.jpg)

**Comment by dannyl07** [comment]
Need to add this to web.config:  Note, the maxAllowedContentLength is set in bytes.
<system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <modules runAllManagedModulesForAllRequests="true" />
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="1073741824" />
      </requestFiltering>
    </security>
  </system.webServer>

**Comment by dannyl07** [comment]
&lt;system.webServer&gt;
    &lt;validation validateIntegratedModeConfiguration="false" /&gt;
    &lt;modules runAllManagedModulesForAllRequests="true" /&gt;
    &lt;security&gt;
      &lt;requestFiltering&gt;
        &lt;requestLimits maxAllowedContentLength="1073741824" /&gt;
      &lt;/requestFiltering&gt;
    &lt;/security&gt;
  &lt;/system.webServer&gt;
