### ISSUE TITLE
please update database with new variable names and associated info.

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#18]
I will share in google docs to you. please let me know if you have questions. I included 2 fields for data checks. it's on the first sheet of the workbook labeled "goldstandard- questions" 

I hope the format is ok.

**Comment by wliu-levansoft** [comment]
@mrsminiberger got it.  will get back to you.

@dannyl07 the file is in the SourceTree.

**Comment by mrsminiberger** [comment]
can we make the media type, "PATH Ad-hoc Wave1"?

**Comment by dannyl07** [comment]
Yes, is that equivalent to Images-smoking?

**Comment by mrsminiberger** [comment]
sort of- I'm trying to be more specific... is that ok?

**Comment by dannyl07** [comment]
Yes we can update them to say anything.  Currently functionally, we have the following media types:
Website
Image_Tobacco <-- PATH Ad-hoc Wave1
Image_Alcohol
Video_Tobacco
Video_Alcohol

**Comment by mrsminiberger** [comment]
how come I can't see them?

**Comment by dannyl07** [comment]
Sorry, the latest changes will be deployed early next week.

**Comment by dannyl07** [comment]
In reeldb, we used -9997 to represent option values not filled in. Do we want to do the same here or something different like empty value?

**Comment by mrsminiberger** [comment]
I think -9997 is still relevant. Any update on timing of the deploy? I'm getting nervous that we're not going to meet our deadline for coding these images. (no pressure or anything... heh.)

**Comment by dannyl07** [comment]
I'm hoping later today or early tomorrow.

**Comment by dannyl07** [comment]
My daughter is sick today. I'm a bit behind schedule. Would you consider if we deploy everything except for the review inspection before tomorrow which will have the latest variable names in the database?  This way we would no longer replace the entire database when deploying?  I'll need another day or so to build the inspector.

**Comment by wliu-levansoft** [comment]
Yes, let's do that.  Let me know when it's ready to build.

**Comment by mrsminiberger** [comment]
Honestly, we can't do anything until the variable names are updated, so it doesn't really matter to me.

**Comment by dannyl07** [comment]
Latest data and web app has been deployed to production.  The only thing missing is the review inspector.  I'll work on that today and tomorrow.  Hopefully in the next couple of days it'll be ready.

**Comment by dannyl07** [comment]
One comment, in the field named "quality" in group "Product", I renamed the key to "product_quality".  There is another "quality" in the group titled "Design".  We would like to keep a unique name for each given media type.  This allows us to build a more reliable review inspector.  In case you renamed a review variable to something that's the same as a variable from another group we won't have collisions when validating the review.

**Comment by mrsminiberger** [comment]
ok- I'm a little concerned because the spreadsheet that I uploaded to google docs had the "dartmouth variable name" as "product_quality" as you suggested already. How can I see the one you are working from?

**Comment by dannyl07** [comment]
You're right. I had used the wrong column. I will have it fixed by tomorrow morning.

**Comment by mrsminiberger** [comment]
It's CHRISTMAS!!!! Thanks Dan!

**Comment by dannyl07** [comment]
Looks like you created some test data.  Would it be okay to blow away the database and recreate it again or would you like me to try not to do that?

**Comment by dannyl07** [comment]
I ended up fix the data without blowing it away.  If you have time, would you mind double-checking groups and fields against what you've sent me just as a second pair of eyes.  Note: I change the data that's already in the coded reviews as well so we won't have any orphaned data.

Thanks
