### ISSUE TITLE
all reviews

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#20]
I can't find where I can see all of the reviews assigned to a particular image. It only shows me the last one I assigned.

**Comment by dannyl07** [comment]
To view all reviews, you'll have to click on the "last media" link on the left.  The link that starts with "PATH Ad-hoc Wave1 :<title_of_media>"

**Comment by mrsminiberger** [comment]
this link? 

![screen shot 2014-04-15 at 12 34 32 pm](https://cloud.githubusercontent.com/assets/7119634/2709969/e72e8dce-c4bb-11e3-98d8-4c31e29da5f4.png)

gives me this screen:
![screen shot 2014-04-15 at 12 34 42 pm](https://cloud.githubusercontent.com/assets/7119634/2709989/0f0a70ba-c4bc-11e3-9e0a-81e52554e363.png)

I can't see all reviews.

**Comment by dannyl07** [comment]
There may be a caching issue where your browser was caching the content...I'll try to address this.

**Comment by wliu-levansoft** [comment]
For now, try to clear cache by Ctrl+Shift+Delete.

![screenshot_041514_014939_pm](https://cloud.githubusercontent.com/assets/6913896/2710828/5972069a-c4c6-11e3-9c6c-7302bafd5615.jpg)

**Comment by mrsminiberger** [comment]
ok- I cleared my cache and it didn't change anything. Can you give me a screenshot of what you are seeing and how to get to the reviews? And I can either follow it or send you a screenshot of where I get stuck?

**Comment by dannyl07** [comment]
Can you see if this is still an issue?
https://reeldb.dartmouth.edu/Media-coding/media_search/21
![capture](https://cloud.githubusercontent.com/assets/7150555/2711762/77ed7982-c4d1-11e3-8a99-091c61066aeb.JPG)

**Comment by mrsminiberger** [comment]
I'm at work today. I cleared my cache here and I'm still not seeing the reviews like you are. Could this be a Chrome thing?

**Comment by mrsminiberger** [comment]
I just checked firefox and it's not there either.

**Comment by mrsminiberger** [comment]
maybe a font thing?

**Comment by mrsminiberger** [comment]
ok- not a font thing- it's not in the page source either.

**Comment by dannyl07** [comment]
Can you copy and paste the URL from the browser and send it to me?

**Comment by mrsminiberger** [comment]
I just clicked on the one above: https://reeldb.dartmouth.edu/Media-coding/media_search/21 or https://reeldb.dartmouth.edu/Media-coding/media_search/query/*

**Comment by mrsminiberger** [comment]
![image](https://cloud.githubusercontent.com/assets/7119634/2721434/50473350-c57b-11e3-8f89-267850d76a55.png)

**Comment by dannyl07** [comment]
Is this what you see for https://reeldb.dartmouth.edu/Media-coding/media_search/21
![capture](https://cloud.githubusercontent.com/assets/7150555/2721457/815365a4-c57b-11e3-9f14-181f6341807d.JPG)

**Comment by mrsminiberger** [comment]
Nope: 
![image](https://cloud.githubusercontent.com/assets/7119634/2721666/d8b969ae-c57d-11e3-8e4d-25bda0d4e676.png)

**Comment by dannyl07** [comment]
Aha, I found the problem.  Looks like if you're logged in as you who does not have a country specification then you can't see it.

Fixing it now...

**Comment by mrsminiberger** [comment]
ohhhhh.... I should have checked that... since it already bit us in the behind once before. Bad laina.

**Comment by dannyl07** [comment]
I just published the fix.  Could you please take a look?

**Comment by mrsminiberger** [comment]
MUCH better!
