### ISSUE TITLE
creating reviews

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#21]
after I've created a review, I have to go back to "search media" in order to assign the next review. if we could have the "create new review" link spawn a new window and leave the list of media open in the previous window, I think that would speed things up a bit...

![screen shot 2014-04-15 at 11 04 17 am](https://cloud.githubusercontent.com/assets/7119634/2708725/41791c20-c4af-11e3-8a6d-f2791004a3dd.png)

**Comment by dannyl07** [comment]
Fixing this now.  Can you please let me know if I can blow away the database ... probably the last time.  While building the review inspector I found some errors with the imported data.

**Comment by dannyl07** [comment]
Fixed and deployed.
Now the creation/update of the reviews is done by a popup window.  When finished, click on "Done" and the new window will close and the list will refresh showing any changes you've made.

**Comment by dannyl07** [comment]
I just modified this to use a dialog window, it really makes the experience flow better.

**Comment by mrsminiberger** [comment]
It really does. I'm creating reviews now. The only thing I would suggest would make it better would be if the list of reviews from the primary window didn't default back to the top, but instead stayed where it was.

**Comment by dannyl07** [comment]
For now it will automatically scroll to the position which you had. . .there is a slight delay.

**Comment by dannyl07** [comment]
I just published a change where if you click on the "Done" button of the review popup dialog, only the given row will update.  So the page will partially refresh, and you won't lose your scroll position at all.
