### ISSUE TITLE
inspect review error

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#23]
when the coder clicks on the 'inspect review' button, they get an error if they leave the following blank: in the 'main' section, #5 list other tobacco brands, and #7 other brands (not tobacco). 

The error message says "list other tobacco brands can not be empty"

They should be able to be kept blank...

**Comment by wliu-levansoft** [comment]
Fixed.

![screenshot_041614_094816_pm](https://cloud.githubusercontent.com/assets/6913896/2727358/608374de-c5d2-11e3-9801-c4a9c2a87ba3.jpg)
