### ISSUE TITLE
updating tooltip text

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#24]
when I hit save after updating tooltip text, it doesn't save it and closes the field and the text is not updated. (SAD.)

**Comment by wliu-levansoft** [comment]
Which field were you editing?  It worked for me.

![screenshot_041714_030352_pm](https://cloud.githubusercontent.com/assets/6913896/2735681/03e5b2f0-c663-11e3-8933-f478fca1df83.jpg)

**Comment by mrsminiberger** [comment]
I was editing tooltip text for product_count

**Comment by wliu-levansoft** [comment]
I can edit that one too.

![screenshot_041714_034125_pm](https://cloud.githubusercontent.com/assets/6913896/2736069/42ccf596-c668-11e3-9958-6bf038944411.jpg)

**Comment by dannyl07** [comment]
Is it possible that you accidentally clicked on "Cancel" which is right next to "Save"?

**Comment by mrsminiberger** [comment]
That's the notes field, not the tooltip. And I DEFINITELY clicked save. I thought I clicked cancel the first time, so I did it again.

**Comment by wliu-levansoft** [comment]
OK.  I can produce it.  @dannyl07, it says that I have "1487 characters remaining".  But I can only remove characters but not add any.

**Comment by dannyl07** [comment]
Mystery solved.  The UI allowed the field to be 2000 characters long, but the database was only defined to have 512 characters.  So anything longer than 512 characters were being truncated.  I made everything 2000 characters so it should work now.  

I think at the time when I was creating the UI I had told myself that the tooltip should be 2000 characters but forgot to go back and modify the DB script.  This shouldn't happen again...
