### ISSUE TITLE
setting error messages coming up for setting_outdoors

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#25]
![image](https://cloud.githubusercontent.com/assets/7119634/2818967/cc964bae-cee9-11e3-938d-001571c821c5.png)

![image](https://cloud.githubusercontent.com/assets/7119634/2818896/161d1b8c-cee9-11e3-91a9-349517da59e8.png)

**Comment by dannyl07** [comment]
I'll fix it in a few minutes.

**Comment by dannyl07** [comment]
Fixed...
