### ISSUE TITLE
coders review list

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#28]
We are doing double codes. I back up the primary review which duplicates the primary into a reliability and then I change the status of the primary to "assigned". However, the coders no longer see the review I just assigned them. They only see the reliability review. 

Let me know if this is not clear. 
E

**Comment by dannyl07** [comment]
Do you mind sending me an example?   Thanks

**Comment by dannyl07** [comment]
This may be a sorting issue.  I just published a change where the list is sorted by the media type first.  So now you should see the assigned review right next to the reliability review.   I hope this solves your problem...
![capture](https://cloud.githubusercontent.com/assets/7150555/3060062/ad5c7ab6-e1f3-11e3-9620-ae60710a5bdd.JPG)

**Comment by dannyl07** [comment]
Should the coders (non-admin) be able to view/code the reviews tagged as reliability?

**Comment by dannyl07** [comment]
Is this still an issue or has the fix resolved it?

Thanks

**Comment by mrsminiberger** [comment]
Much better. And no- the coders shouldn't get the reliability reviews.

**Comment by dannyl07** [comment]
I just published a change so that reliability reviews cannot be updated if you don't have admin rights to coding.  Also, the reliability reviews will not show up on the list within the home page.  Closing issue.
