### ISSUE TITLE
image file batch upload

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#3]
it appears that I can't do a batch upload, the website wants me to select an individual image instead of a folder or select a number of images. I have 422 images I need to upload! Yikes.

**Comment by wliu-levansoft** [comment]
We'll look into it.

**Comment by dannyl07** [comment]
I'm working on a set of features that allows bulk upload of media files.

**Comment by wliu-levansoft** [comment]
Updated server.  There are a few issues related to the bulk load that we still need to fix.

![screenshot_040514_115017_am](https://cloud.githubusercontent.com/assets/6913896/2623107/fc847cfe-bcd9-11e3-9234-6c27055d1759.jpg)
