### ISSUE TITLE
movie report question

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#30]
So this is not related to the media coding, but I'm wondering how long it would take to add a country field to the query parameters in the movie database. In this window: 
![screen shot 2014-06-06 at 10 21 17 am](https://cloud.githubusercontent.com/assets/7119634/3201272/e907ebac-ed85-11e3-820a-27f9c348d087.png)

And then add, n_vioexp to the overall review report.

Thanks. 
Elaina

**Comment by dannyl07** [comment]
Done.
