### ISSUE TITLE
missing image files

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#32]
For these two ids, 20130129-011464, 20130322-011535- Bindi can not see the images. But I'm seeing them on the backend. Not sure what's going on here.

**Comment by mrsminiberger** [comment]
and this one: 20130404-011756

**Comment by dannyl07** [comment]
Looks like "20130129-011464.jpg" was uploaded twice.  The first one which you created the review under is titled "20130129-011464.jpg (1)".  The review is marked as "Completed" so Bindi can no longer see it.  See https://reeldb.dartmouth.edu/Media-coding/media_search/query/20130129-011464*

Not sure what happened to 20130322-011535, but same situation where two media were created.  But the second one didn't have the media file attached.  I fixed it manually.

20130404-011756 has the same story as the first one.  Two media entries were created.  You created reviews under the second one. (The one with the (1) as postfix).  However, the review was completed.

Let me know if you want me to go into the database and fix the ones where you created duplicate media entries. . .I can delete the ones that were not used...  I see a total of 9 entries where this has happened.

I'll leave this issue open until I hear from you before I will close it.

Thanks

**Comment by mrsminiberger** [comment]
hmm- more info... I'm trying to delete these and I'm getting that same database error... 
![screen shot 2014-06-16 at 3 48 02 pm](https://cloud.githubusercontent.com/assets/7119634/3292426/3cdc1c9c-f58f-11e3-81b6-4aa467838854.png)

**Comment by mrsminiberger** [comment]
ah- sorry- yes- I think deleting the duplicates will work. Wanna let me know when you've finished?

**Comment by dannyl07** [comment]
You can't delete it because you've assigned reviews to them.  I can do it in the back end.

**Comment by dannyl07** [comment]
I was able to fix 7/9 of them.  The only two left is:
20130401-011417.jpg (1)
20130404-011970.jpg (1)

They both have a primary review with "Completed" status.  Would you like me to delete one entry?  Merge two review entires under one media?  We'll have to assign a new status/type.  Let me know.

**Comment by mrsminiberger** [comment]
that sounds good. I can set the garbage review to test or something.  Thanks Dan. I appreciate it.

**Comment by dannyl07** [comment]
So would you like me to merge the review and set the other one as secondary or delete the duplicate review?

**Comment by dannyl07** [comment]
Do you mind getting back to me on this so I can fix?

Thanks

**Comment by mrsminiberger** [comment]
sorry about that- yes please do.

**Comment by dannyl07** [comment]
Each of those entries has one review attached.  All primary + completed + same coder.
So the options are

1.)  Move the review from one to another, change the moved review from primary to secondary
2.)  Delete the review entry along with the media entry since they may be duplicate anyway.

Please let me know before I can fix.

Thanks

**Comment by mrsminiberger** [comment]
We should delete the review that has all -9997 as the entries or the one that has (1) at the end.

**Comment by dannyl07** [comment]
Sorry it took so long.  It's now clean.  I deleted the reviews attached to the ...(1) media entries even though it had similar (not exactly the same) entries as the mirroring media entry.  But we should be all set now.
