### ISSUE TITLE
error adding variable options

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#33]
![screen shot 2014-06-16 at 12 32 08 pm](https://cloud.githubusercontent.com/assets/7119634/3290053/e0329e32-f573-11e3-8589-9b1db6a5f285.png)

There is no option 6 for product type.

**Comment by dannyl07** [comment]
This one is working as designed.  The popup screen wasn't long enough so you couldn't see that this list actually has 7 values already.  Therefore "6" was already taken.  You can resize the popup screen by dragging the bottom.
