### ISSUE TITLE
error closing reviews

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#34]
AURCFB-0015, AMSFFB- 0048, SWMTFB -003

I entered complete and then save and got this message:

Internal Server Error
Sys.WebForms.PageRequestManagerServerErrorException: An unknown error occurred while processing the request on the server. The status code returned from the server was: 500

**Comment by dannyl07** [comment]
So this is caused by the fact you already have a review in the database for that media that's tagged as "Primary" and "Completed".  You can only have one review that has the same MediaId-ReviewType-ReviewStatus.

I made a quick change in the code so that you'll get a better error message.

**Comment by dannyl07** [comment]
So does it make sense to prevent the admin to create multiple reviews with the same type?  So should the application send an error if you try to create a review with type "Primary" when there is already one in the database?

Right now it only checks to see if they have the same type+status+country.
