### ISSUE TITLE
movie rating

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#35]
HI there. 

Could you add m_rating and m_rank from the movie table to all of the report tables?  Here: https://reeldb.dartmouth.edu/DVMP2013/MovieReports.aspx

**Comment by dannyl07** [comment]
Done.  m_rating was only missing on the overall report and m_rank was added to all of the report types.

**Comment by mrsminiberger** [comment]
Thanks!!!
