### ISSUE TITLE
IMDB search broken?

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#36]
https://reeldb.dartmouth.edu/DVMP2013/SearchImdb.aspx

imdb search seems to be broken- returning 0 results: 
![screen shot 2014-12-18 at 10 51 34 am](https://cloud.githubusercontent.com/assets/7119634/5491014/e5c66df8-86a3-11e4-9e1c-11ad2c354b2e.png)

**Comment by dannyl07** [comment]
Having trouble connecting to your production server.  We're working on it and will get back to you soon.  Thanks.

**Comment by dannyl07** [comment]
It looks like while running the job last time the database query timedout.  I restarted the job and looks like everything is well now.
