### ISSUE TITLE
import excel into MS SQL Server Management Studio

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#37]
Can you tell me what I'm doing wrong? I need to update the "gross" variable in the movie table. I created an excel spreadsheet with the data I need. I use the import wizard in management Studio to import into the Temp_import database I created. By all rights, it LOOKS Like it works fine... no errors. The right number of rows importing, but the tables are just NOT THERE. Could it be sticking it somewhere else? Pasting the status report: 

The execution was successful
- Initializing Data Flow Task (Success)
- Initializing Connections (Success)
- Setting SQL Command (Success)
- Setting Source Connection (Success)
- Setting Destination Connection (Success)
- Validating (Success)
- Prepare for Execute (Success)
- Pre-execute (Success)
- Executing (Success)
- Copying to [Temp_import].[dbo].[1](Success)
  2367 rows transferred 

Messages
Information 0x402090df: Data Flow Task: The final commit for the data insertion has started.
 (SQL Server Import and Export Wizard)
- Copying to [Temp_import].[dbo].['1$'](Success)
  2367 rows transferred 

Messages
Information 0x402090df: Data Flow Task: The final commit for the data insertion has started.
 (SQL Server Import and Export Wizard)

Information 0x402090e0: Data Flow Task: The final commit for the data insertion has ended.
 (SQL Server Import and Export Wizard)

Information 0x402090e0: Data Flow Task: The final commit for the data insertion has ended.
 (SQL Server Import and Export Wizard)
- Post-execute (Success)
- Cleanup (Success)
  Messages
  Information 0x4004300b: Data Flow Task: "component "Destination - 1" (20)" wrote 2367 rows.
  (SQL Server Import and Export Wizard)

Information 0x4004300b: Data Flow Task: "component "Destination 1 - '1$'" (61)" wrote 2367 rows.
 (SQL Server Import and Export Wizard)

**Comment by dannyl07** [comment]
Elena,

I'll take a look tomorrow morning to see if it's a permission issue. 

In the meantime, do you mind sending me the excel document so I can reimport if needed?

Thanks

**Comment by dannyl07** [comment]
I was able to get into the server and saw that you have imported four tables.  The database is Teamp_import and the tables are :
dbo.[1]
dbo.['1$']
dbo.[first]
dbo.['second']

I was able to select the rows.  Please see screenshot attached.
![capture](https://cloud.githubusercontent.com/assets/7150555/6057268/5c82053a-acea-11e4-80d1-7c9d14e53a1a.JPG)

**Comment by mrsminiberger** [comment]
Weird... I guess there's a refresh issue... I'll check it again today.
