### ISSUE TITLE
changing variable names

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#4]
Is there a way by which the key field can be modified with the website tool? The investigators changed some of the variable names on me. 
![image](https://cloud.githubusercontent.com/assets/7119634/2608391/24478b3a-bb6a-11e3-96e4-1eb4fe8c7186.png)

**Comment by wliu-levansoft** [comment]
The key field should stay the same especially if the field has been used in a review.  You can change the field name to anything you want though.  You can always find the matching key field with a given field name here.

**Comment by dannyl07** [comment]
Since we have not gone live yet.  We should come up with a final list of key and values which we can make the final change before publishing live for coding.  We should blow away the testing database and start fresh once we're ready to go live.

**Comment by mrsminiberger** [comment]
ok. I will do some testing this weekend. Jim wants us to go live ASAP. How should I get you a list of the  "keys". They have to match our collaborator's keys. (Is "key" the same as variable name?)

**Comment by dannyl07** [comment]
A Key is essentially a column name if we were to store the coding values flat in a database table.  They are unique, all small-case, short, and usually is free of space, punctuation and special characters.  The key will probably be used in the top row of the reporting view.

The label on the other hand can be long and more descriptive.

**Comment by mrsminiberger** [comment]
ok- if I give them to you in an excel spreadsheet with the label in one column and key in the other, is that useful?

**Comment by dannyl07** [comment]
Yes, we built the demo with an excel sheet.  If you give me the latest, I can modify my import script to include your changes.
