### ISSUE TITLE
ext_id and filename assignment

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#5]
The external id in most cases will be the same as the image filename minus ".jpg" or whatever extension it has. Is there a way to automate that? 

So 
Filename: "AFBD20057.jpeg" 
ext_id= "AFDB20057"

**Comment by wliu-levansoft** [comment]
We can update the ext_id field with filename minus extension after they enter the filename.

**Comment by dannyl07** [comment]
Sounds like ext_id should be an entity of "Media" instead of part of a coding variable per review.  Looks like the Media admin assigns the external ID once during the creation of the media.  Is that correct?

**Comment by mrsminiberger** [comment]
yeah- it's not really a coding variable per se. Most of the ad companies we contract with assign their ID and then make the filename exactly the same. So (ext_id)= (filename.JPEG)- (.jpeg)  So maybe a checkbox when I upload that says, "do you want to assign the ext_id as the filename minus the extension?"

**Comment by dannyl07** [comment]
I will move the ext_id as part of the media entity, and as you upload the image, we will pre-populate with the file name (stripping the extension).  The field is then open for you to edit as you'd like.
