### ISSUE TITLE
Age 

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#6]
What does Key mean? 
![image](https://cloud.githubusercontent.com/assets/7119634/2608462/1aac34f8-bb6b-11e3-872d-eea3cec00406.png)

**Comment by mrsminiberger** [comment]
That is, when we enter the data and I extract it at the end of the day, I would like the <18 option to say "1" not "<18".

**Comment by dannyl07** [comment]
Not sure how the key for <18 became like that.  In my seed data it should be "1".  I think it's possible that somebody deleted the <18 and recreated it with the key and label being the same?  Attached is a screenshot of what I have after the data import:
![capture](https://cloud.githubusercontent.com/assets/7150555/2609302/cf5e8924-bb74-11e3-926e-bcd3ce3902ec.JPG)

**Comment by mrsminiberger** [comment]
yeah- I deleted it because they got rid of the "not sure/unclear" option. But even so, I'm not sure it makes sense in that screen shot...

**Comment by dannyl07** [comment]
Yes, I just realized that the key and label were swapped.  I just fixed this in the new import script. (I also removed "Not sure/unclear" 
I'll close this issue.
