### ISSUE TITLE
questions contingent upon the answer of other questions

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#7]
For the age and race questions, we only want to coders to be able to answer them when there are any men or women. How do we create those types of contingencies/ dependencies? 
![image](https://cloud.githubusercontent.com/assets/7119634/2608603/aae6477e-bb6c-11e3-9a58-e1c1afe72e27.png)

**Comment by dannyl07** [comment]
Again, this will have to be enforced by the "Inspection" process.

**Comment by mrsminiberger** [comment]
That's fine! I'm working on the spreadsheet now, so I'll put those contingencies in it.

**Comment by dannyl07** [comment]
Created inspection feature to handle this.  All reviews must go through inspection before it's "Completed".
