### ISSUE TITLE
"Select up to 2"

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#8]
For the questions that were "select up to 2", is there programming to ensure that they don't select more than 2? 
![image](https://cloud.githubusercontent.com/assets/7119634/2609065/ea3534da-bb71-11e3-8e90-3bedd4e77fdf.png)

**Comment by dannyl07** [comment]
It'd be very difficult to build rules for a subset of fields that's mixed with other fields within the same group.  

However, we can create a list of rules which we can implement as an "Inspection" step that would enforce these rules before a review can be completed.  Much like we are doing with the Movies and TV shows.

Would that be okay?

**Comment by mrsminiberger** [comment]
That would be absolutely FINE! should I include those checks in the key spreadsheet from the other "issue"?

**Comment by dannyl07** [comment]
Yes, we can build the inspection logic based on the rules you specify in the key spreadsheet.

**Comment by dannyl07** [comment]
Review inspector has been implemented.
![capture](https://cloud.githubusercontent.com/assets/7150555/2711780/a8a9889a-c4d1-11e3-91f8-abf6c3d48dc4.JPG)
