### ISSUE TITLE
create different variables for different media projects

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#9]
This is not urgent for the moment, but I figure I'll mention it in case it is necessary for you guys to fix now.

When I create a new media project, I'm going to want to be able to change the variables that exist in that project. So the project we are working on now is focused on the attributes of tobacco advertising. The next one might be focused on alcohol content and be created by a completely different group. So I need to be able to assign variables per image group.

**Comment by dannyl07** [comment]
I think the best approach for this is to move the current image media type to image-tobacco. And the create a separate image-alcohol which would have its own groups and fields. Does that make sense?

**Comment by mrsminiberger** [comment]
It sounds good in the abstract. I'm not sure I understand the mechanics though... which I guess I don't need to.

**Comment by dannyl07** [comment]
The idea is that each media type has its own groups of variables. We created two media type to start with. A generic image and a generic website.  Logically speaking. You would have two different types of image. A smoking-image type and a alcohol-image type. So the best solution is to move the current image type into image-smoking. We will create a image-alcohol and create/import groups and variables for that. This would be all data changes with minimal amount of code change.

**Comment by dannyl07** [comment]
Fixed. . .created new review type.  Will reflect when new database with seed data is deployed.
